[global]

temp = "hello world"

[[wallpapers]]

    filename = "hello world"

    [[wallpapers.schedules]]

        [[wallpapers.schedules.rules]]

            Week = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]


