[global]

temp = "hello world"

[[wallpapers]]

    filename = "hello world"

    [[wallpapers.schedules]]

        [[wallpapers.schedules.rules]]

            Day = { from = "01:00", to = "15:00" }

    [[wallpapers.schedules]]

        [[wallpapers.schedules.rules]]

            Day = { from = "05:00", to = "15:00" }

        [[wallpapers.schedules.rules]]

            Year = [1, 3, 4]

